import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781578985277 implements MigrationInterface {
    name = 'InitialSchema1781578985277'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`address\` text NULL, \`loyalty_points\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total_purchases\` decimal(12,2) NOT NULL DEFAULT '0.00', \`last_purchase_date\` timestamp NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp NULL, UNIQUE INDEX \`IDX_8536b8b85c06969f84f0c098b0\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` char(36) NOT NULL, \`name\` varchar(128) NOT NULL, \`description\` text NOT NULL, \`company_id\` char(36) NULL, \`is_system_role\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime NULL, UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` char(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`first_name\` varchar(128) NULL, \`last_name\` varchar(128) NULL, \`phone\` varchar(20) NULL, \`company_id\` char(36) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`last_login\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime NULL, INDEX \`idx_last_login\` (\`last_login\`), INDEX \`idx_company_active\` (\`company_id\`, \`is_active\`), UNIQUE INDEX \`idx_email\` (\`email\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`products\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`sku\` varchar(100) NOT NULL, \`barcode\` varchar(100) NULL, \`category_id\` varchar(255) NULL, \`price\` decimal(10,2) NOT NULL, \`cost\` decimal(10,2) NULL, \`stock_quantity\` int NOT NULL DEFAULT '0', \`reorder_level\` int NOT NULL DEFAULT '0', \`tax_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`is_active\` tinyint NOT NULL DEFAULT 1, \`image_url\` varchar(500) NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, UNIQUE INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` (\`sku\`), UNIQUE INDEX \`IDX_adfc522baf9d9b19cd7d9461b7\` (\`barcode\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` varchar(36) NOT NULL, \`order_id\` varchar(36) NOT NULL, \`product_id\` varchar(36) NOT NULL, \`quantity\` int NOT NULL, \`unit_price\` decimal(10,2) NOT NULL, \`subtotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`tax_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total\` decimal(10,2) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` varchar(36) NOT NULL, \`order_id\` varchar(36) NOT NULL, \`payment_method\` enum ('cash', 'card', 'transfer', 'other') NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`payment_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`transaction_id\` varchar(255) NULL, \`status\` enum ('pending', 'completed', 'failed', 'refunded') NOT NULL DEFAULT 'completed', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(36) NOT NULL, \`customer_id\` char(36) NULL, \`order_number\` varchar(255) NOT NULL, \`order_date\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, \`status\` enum ('draft', 'pending', 'confirmed', 'completed', 'cancelled', 'voided') NOT NULL DEFAULT 'draft', \`subtotal\` decimal(10,2) NOT NULL DEFAULT '0.00', \`tax_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`discount_amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`total_amount\` decimal(10,2) NOT NULL, \`payment_status\` enum ('unpaid', 'partially_paid', 'paid', 'refunded') NOT NULL DEFAULT 'unpaid', \`notes\` text NULL, \`created_by\` char(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_75eba1c6b1a66b09f2a97e6927\` (\`order_number\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`companies\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NULL, \`phone\` varchar(20) NULL, \`email\` varchar(255) NULL, \`tax_id\` varchar(50) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` int NOT NULL AUTO_INCREMENT, \`companyId\` varchar(36) NOT NULL, \`companyName\` varchar(255) NOT NULL, \`nit\` varchar(50) NULL, \`address\` text NULL, \`phone\` varchar(20) NULL, \`email\` varchar(255) NULL, \`website\` varchar(255) NULL, \`logoUrl\` varchar(500) NULL, \`city\` varchar(100) NULL, \`country\` varchar(100) NULL, \`taxRate\` decimal(5,2) NOT NULL DEFAULT '19.00', \`taxIncludedInPrice\` tinyint NOT NULL DEFAULT 1, \`currency\` varchar(20) NOT NULL DEFAULT 'COP', \`locale\` varchar(10) NOT NULL DEFAULT 'es-CO', \`paymentCash\` tinyint NOT NULL DEFAULT 1, \`paymentCard\` tinyint NOT NULL DEFAULT 1, \`paymentTransfer\` tinyint NOT NULL DEFAULT 1, \`paymentCredit\` tinyint NOT NULL DEFAULT 0, \`paymentTransferInstructions\` text NULL, \`trackInventory\` tinyint NOT NULL DEFAULT 1, \`allowNegativeStock\` tinyint NOT NULL DEFAULT 1, \`defaultReorderPoint\` int NOT NULL DEFAULT '5', \`requireCustomer\` tinyint NOT NULL DEFAULT 1, \`printReceiptAutomatically\` tinyint NOT NULL DEFAULT 0, \`receiptFooter\` text NULL, \`largeSaleThreshold\` int NOT NULL DEFAULT '500000', \`loyaltyEnabled\` tinyint NOT NULL DEFAULT 1, \`loyaltyPointsPerCurrency\` decimal(5,2) NOT NULL DEFAULT '1.00', \`loyaltyPointValue\` decimal(5,2) NOT NULL DEFAULT '0.01', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`idx_settings_company\` (\`companyId\`), UNIQUE INDEX \`IDX_43c062400c119a00dbb83ffd13\` (\`companyId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`product_categories\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`parent_id\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`companyId\` varchar(36) NOT NULL, \`userId\` varchar(36) NULL, \`type\` enum ('low_stock', 'out_of_stock', 'sale_milestone', 'new_user', 'system', 'reorder_alert', 'large_sale') NOT NULL, \`priority\` enum ('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium', \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`data\` json NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`readAt\` datetime NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_notif_created\` (\`createdAt\`), INDEX \`idx_notif_user\` (\`userId\`), INDEX \`idx_notif_company_read\` (\`companyId\`, \`isRead\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stock_movements\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`product_id\` varchar(255) NOT NULL, \`location_id\` varchar(255) NOT NULL, \`movement_type\` enum ('IN', 'OUT', 'ADJUST', 'DAMAGE', 'RETURN') NOT NULL, \`quantity\` int NOT NULL, \`reference_id\` varchar(255) NULL, \`notes\` varchar(255) NULL, \`created_by\` varchar(255) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`locationId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warehouse_locations\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`warehouse_id\` varchar(255) NOT NULL, \`location_code\` varchar(255) NOT NULL, \`capacity\` int NOT NULL, \`current_stock\` int NOT NULL DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp NULL, \`warehouseId\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`warehouses\` (\`id\` varchar(36) NOT NULL, \`company_id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NULL, \`manager_id\` varchar(255) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`user_id\` char(36) NOT NULL, \`role_id\` char(36) NOT NULL, INDEX \`IDX_87b8888186ca9769c960e92687\` (\`user_id\`), INDEX \`IDX_b23c65e50a758245a33ee35fda\` (\`role_id\`), PRIMARY KEY (\`user_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_9263386c35b6b242540f9493b00\` FOREIGN KEY (\`product_id\`) REFERENCES \`products\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_b2f7b823a21562eeca20e72b006\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_f5d519a61e918f7efb299de31a0\` FOREIGN KEY (\`company_id\`) REFERENCES \`companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_574a2f0932043d4e4baf188ee05\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`stock_movements\` ADD CONSTRAINT \`FK_50fab165d7aa9fea5f749b1574c\` FOREIGN KEY (\`locationId\`) REFERENCES \`warehouse_locations\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`warehouse_locations\` ADD CONSTRAINT \`FK_ac9f8443edc269de2443e3bf25b\` FOREIGN KEY (\`warehouseId\`) REFERENCES \`warehouses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`warehouse_locations\` DROP FOREIGN KEY \`FK_ac9f8443edc269de2443e3bf25b\``);
        await queryRunner.query(`ALTER TABLE \`stock_movements\` DROP FOREIGN KEY \`FK_50fab165d7aa9fea5f749b1574c\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_574a2f0932043d4e4baf188ee05\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_f5d519a61e918f7efb299de31a0\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_b2f7b823a21562eeca20e72b006\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_9263386c35b6b242540f9493b00\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`DROP INDEX \`IDX_b23c65e50a758245a33ee35fda\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_87b8888186ca9769c960e92687\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`warehouses\``);
        await queryRunner.query(`DROP TABLE \`warehouse_locations\``);
        await queryRunner.query(`DROP TABLE \`stock_movements\``);
        await queryRunner.query(`DROP INDEX \`idx_notif_company_read\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`idx_notif_user\` ON \`notifications\``);
        await queryRunner.query(`DROP INDEX \`idx_notif_created\` ON \`notifications\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`product_categories\``);
        await queryRunner.query(`DROP INDEX \`IDX_43c062400c119a00dbb83ffd13\` ON \`settings\``);
        await queryRunner.query(`DROP INDEX \`idx_settings_company\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP TABLE \`companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_75eba1c6b1a66b09f2a97e6927\` ON \`orders\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_adfc522baf9d9b19cd7d9461b7\` ON \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_c44ac33a05b144dd0d9ddcf932\` ON \`products\``);
        await queryRunner.query(`DROP TABLE \`products\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_email\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_company_active\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`idx_last_login\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_8536b8b85c06969f84f0c098b0\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
    }

}
